spring:
  main:
    allow-bean-definition-overriding: true
  redis:
    timeout: 10000
  cloud:
    #Sentinel 配置
    sentinel:
      transport:
        dashboard: ${movies.sentinel.dashboard}
      eager: true  #服务启动直接建立心跳连接
    #gateway配置
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能,根据微服务名路由
      globalcors:
        #跨域
        cors-configurations:
          '[/**]': #匹配所有path请求
            allowedOrigins: "*" #允许域名访问
            allowed-headers: "*"
            allow-credentials: true
            #允许的请求方式GET,POST,PUT,DELETE
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE

      #全局配置熔断: 服务未开启、连接超时(20s)等
      default-filters:
        #服务降级 路由超时后降级
        - name: Hystrix
          args:
            name: default
            fallbackUri: forward:/default/fallback

      #服务路由配置
      routes:
        #演员服务
        - id: actor-service
          uri: lb://actor-service #负载均衡分发请求
          predicates:
            - Path=/api-actor/**  #该服务前缀
          filters:
            - StripPrefix=1
        # 定时任务服务
        - id: code-generate-service
          uri: lb://code-generate-service #负载均衡分发请求
          predicates:
            - Path=/api-code/**  #该服务前缀
          filters:
            - StripPrefix=1
        #文件服务
        - id: file-service
          uri: lb://file-service #负载均衡分发请求
          predicates:
            - Path=/api-file/**  #该服务前缀
          filters:
            - StripPrefix=1
        #搜索服务
        - id: search-service
          uri: lb://search-service #负载均衡分发请求
          predicates:
            - Path=/api-search/**  #该服务前缀
          filters:
            - StripPrefix=1